origin = "http://deploy.durhack-dev.com"
webhook_secret_token = "not-a-real-secret-token"
executable_search_paths = []

[listen]
host = "localhost"
port = 3400

[proxy_fix]  # in development, behind both nginx and https://smee.io or similar
x_for = 2
x_proto = 2

[deployments]
