origin = "http://deploy.durhack-dev.com"
webhook_secret_token = "not-a-real-secret-token"
# override this in local.toml: "pyamqp://myuser:mypassword@localhost/myvhost"
celery_task_broker_uri = "pyamqp://guest@localhost//"

[listen]
host = "localhost"
port = 3400

[proxy_fix]  # in development, behind both nginx and https://smee.io
x_for = 2
x_proto = 2
