# deploy.durhack.com is the instance of durhack-deployer running on the persistent VPS
origin = "https://deploy.durhack.com"

[deployments.durhack-api]
repository = "ducompsoc/durhack"
enabled = true
branch = "main"
path = "/var/www/api.durhack.com"
instance_name = "api.durhack.com"

[deployments.deployer]
repository = "ducompsoc/durhack-deployer"
enabled = true
branch = "main"
path = "/var/www/deploy.durhack.com"
systemd_unit_name = "durhack-deployer-queue-workers"
uwsgi_config_path = "/etc/uwsgi/vassals/deploy.durhack.com.ini"

[deployments.nginx]
repository = "ducompsoc/durhack-nginx"
enabled = true
branch = "main"
path = "/home/durhack/projects/durhack-nginx"

[[deployments.nginx.sites]]
rule = "include"
select = [
    "admin.auth.durhack.com",
    "api.durhack.com",
    "api.durhack-staging.com",
    "auth.durhack.com",
    "deploy.durhack.com",
]
